### ISSUE TITLE
Consider adding cake-contrib user as co-owner on NuGet.org

### ISSUE THREAD

**Issue by gep13** [aabenoja/Cake.Parallel#2]
@aabenoja now that you have pushed the NuGet Package to NuGet.org (https://github.com/aabenoja/Cake.Parallel/issues/1), I was wondering if you would consider something else...

Have you seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by aabenoja** [comment]
@gep13 Done.

**Comment by gep13** [comment]
@aabenoja that is great news! Thank you very much!
