### ISSUE TITLE
Project URL is missing from nuspec

### ISSUE THREAD

**Issue by Jericho** [aabenoja/Cake.Parallel#8]
The cake-contrib organization has an automated process to audit all cake addins to verify it they follow best practices, references latest cake DLLs, etc. Unfortunately this process is unable to audit your addin because it's unable to correlate the nuget package with the source project on github.

To solve this issue, can you please add `projectUrl` in your nuspec and republish your nuget package? This will allow nuget.org to display the `Project Site` on your package's download page and therefore allow the automated audit process to correlate the package and the source project.

**Comment by aabenoja** [comment]
@Jericho Done with [0.20.3](https://www.nuget.org/packages/Cake.Parallel.Module/0.20.3). It looks like it was lost during the migration to .net core.

**Comment by Jericho** [comment]
Excellent. The automated process will run tonight at midnight (GMT) and it should be able to audit your addin. In case you haven't seen it already, the report generated by the audit process is available [here](https://github.com/cake-contrib/Home/blob/master/Audit.md).
